### ISSUE TITLE
Current master does not link

### ISSUE THREAD

**Issue by roth-a** [nbfc-linux/nbfc-linux#15]
Linking of the current master fails with the error
```
/usr/bin/ld: /tmp/ccjm2fWy.o: in function `Fan_ECFlush':
build.c:(.text+0x1fc2): undefined reference to `roundf'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:65: nbfc_service] Error 1
make[1]: Leaving directory '/home/<user>/nbfc-linux/src'
make: *** [Makefile:54: src/nbfc_service] Error 2
```

**Comment by natto1784** [comment]
Works fine with clang 7.1.0 and gcc 10.3.0. 938e9118db0b8d2b00bc966e3d045932223f5b28 should fix it; moved the flags to the end for older compiler versions.
