### ISSUE TITLE
does not work  on Acer Nitro V ANV15-51

### ISSUE THREAD

**Issue by NatanAmorim** [nbfc-linux/nbfc-linux#188]
> [!NOTE]
> **I've updated this post to keep it simple and focus on the most useful information for everyone.**
>
> [PXDiv posted](https://github.com/nbfc-linux/nbfc-linux/issues/188#issuecomment-2853360577) two software solutions, I am using his `Div Acer Manager Max (DAMX)` to control my fans. 

I'm to trying make my [Acer Nitro ANV15-51](https://br-store.acer.com/notebook-acer-anv15-51-7037-ci713620h-16gb-512gb-ssd-6g-gddr6-rtx4050-gutta-black-fhd-156-nh-qs8al-001-p/p?srsltid=AfmBOopzKNJdmlk5NTKM2TjWGYT3aokadyX8DfADulcIMxIQUOM3cqjU) fans work with nbfc-linux, I'm willing to provide more info (or edit with less info) for anyone also trying to find a solution that can control fans on this laptop.

This Laptop came with [Linux Gutta](https://br-store.acer.com/sistema-operacional-linux-gutta?srsltid=AfmBOoqE1qYT_-ojDipVeP2hDvuB_X4hlkkWdU_7yE1NwPmYl8ls7C14), but it had a partition called "WINDRIVER" with Windows drivers, the Acer support page lists a ton a of software for Windows but none for Linux, so I tried Windows and it worked perfectly, but now I'm back to Linux and trying to make GNU/Linux work with this laptop. The fans kinda work on Linux but they are so weak and silent, on Windows I can use [Acer NitroSense](https://community.acer.com/en/kb/articles/78-nitrosense-software) and it works really well, if I put both on gaming mode and performance in NitroSense my fans become a Jet Engine, but on Linux I got nothing like that so far...

I tried, Installing the RPM on Nobora and Fedora, Installing the DEB on PopOS and Ubuntu and even tried cloning the git and doing a build with the latest code on multiple distros, but nothing has worked so far, here's more details:

## My laptop

Hardware Information:

```
Laptop Model: Acer Nitro V ANV15-51-7037
Memory: 15695MiB (16.0 GiB)
CPU: 13th Gen Intel i7-13620H (12) @ 4.700GHz
GPU: Intel Raptor Lake-P [UHD Graphics]
GPU: NVIDIA GeForce RTX 4050 Max-Q / Mobile
```

Software Information:

```
OS: Ubuntu 25.04
BIOS: V1.26
Kernel: 6.14.0.15-generic
Desktop Environment (DE): GNOME 48
Windowing System: Wayland
NVIDIA Driver Version: 570.133.07
NVIDIA CUDA Version: 12.8
```

This might be useful [sensors-detect.txt (attachment)](https://github.com/user-attachments/files/19406427/sensors-detect.txt), is the output of [lm_sensors](https://wiki.archlinux.org/title/Lm_sensors) when using `sudo sensors-detect`.

## What i tried

- `sudo nbfc config --recommend` gave me

```
Note: The command 'nbfc config -r' outputs recommended configurations
based solely on comparing your model name with configuration file names.
This recommendation does not imply any further significance or validation
of the configurations beyond the string matching.

Acer Nitro AN715-51
Acer Nitro AN515-51
Acer Nitro AN515-57
Acer Nitro AN515-58
Acer Nitro AN515-42
Acer Nitro AN515-43
Acer Nitro AN515-45
```

- Tried `sudo nbfc config --set "Acer Nitro V ANV15-51"` and `sudo nbfc config --set "Acer Nitro ANV15-51"` just to check, but as I expected no config was found.
- Okay, so I tried every option in the recommended list, but none worked, here's an example

`sudo nbfc config --set "Acer Nitro AN515-58"`

`nbfc status -a`

```sh
Read-only                : false
Selected Config Name     : Acer Nitro AN515-58
Temperature              : 38.33

Fan Display Name         : CPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 4.20
Target Fan Speed         : 0.00
Fan Speed Steps          : 6122

Fan Display Name         : GPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 15.55
Target Fan Speed         : 0.00
Fan Speed Steps          : 6122
```

** A while later while gaming**

`nbfc status -a`

```sh
Read-only                : false
Selected Config Name     : Acer Nitro AN515-58
Temperature              : 62.83

Fan Display Name         : CPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 4.21
Target Fan Speed         : 50.00
Fan Speed Steps          : 6122

Fan Display Name         : GPU fan
Auto Control Enabled     : true
Critical Mode Enabled    : false
Current Fan Speed        : 15.55
Target Fan Speed         : 50.00
Fan Speed Steps          : 6122
```

`Target Fan Speed` is at 50% and the temperature is higher (which the hand test can confirm it was hot), but that made no difference... even `sudo nbfc set -s 100` does not do set the `Current Fan Speed`.

More about the GUI [down below](https://github.com/nbfc-linux/nbfc-linux/issues/188#issuecomment-2745246681).

**Comment by RuberForumfree** [comment]
I have the same exact problem, tough I'm new to linux and I'm using Mint for this, I'm scared to open any games on my laptop now. Mine it's an Acer Nitro 5 AN515-55

**Comment by RuberForumfree** [comment]
Regarding [this guy](https://www.reddit.com/r/AcerNitro/comments/it9hnc/regarding_linux_support/) on reddit, setting the fan speed at "Acer Predator G3-572" should work? I have no idea on how to impementing myself this on my laptop but I'm trying

**Comment by ana-lys** [comment]
Have you tried to build the latest code? Some compilation errors at first, but after a few quick fixes works like a charm for me. It used to not work on its own in earlier versions and needed NitroSense on Windows to kickstart.

**Comment by viv223345** [comment]
Same problem here.

Specs:
```
Acer Nitro V 15
ANV15-51-50N9
RTX 4050
i5-13420H
16/512
```

My laptop gets INSANELY hot when running just a browser and obs. Fans won't ramp up at all.

**Comment by NatanAmorim** [comment]
> I have the same exact problem, tough I'm new to linux and I'm using Mint for this, I'm scared to open any games on my laptop now. Mine it's an Acer Nitro 5 AN515-55

`Acer Nitro 5 AN515-55`Is a **WAY** older model (the firmware could be very different), so I don't think my solution would work on your laptop, also your laptop is probably way closer to the ones already supported by nbfc-linux, have you tried any of the list of recomended?

```
Acer Nitro AN715-51
Acer Nitro AN515-51
Acer Nitro AN515-57
Acer Nitro AN515-58
Acer Nitro AN515-42
Acer Nitro AN515-43
Acer Nitro AN515-45
```

**Comment by NatanAmorim** [comment]
> Have you tried to build the latest code? Some compilation errors at first, but after a few quick fixes works like a charm for me. It used to not work on its own in earlier versions and needed NitroSense on Windows to kickstart.

Yup, I tried on
- Nobora
- Fedora
- CachyOS
- PopOS 24.04 (cosmic alpha 7)
- Ubuntu 24.04.2

I finally got `sudo nbfc-qt` working on Ubuntu, but found out it does the same as the CLI and none of the already existing configs work, the GUI has this "Temperature sources" tab I didn't see anything mentioning in the CLI, maybe I config there? only one way to find out, trial and error...

https://github.com/user-attachments/assets/d6d7d1bc-f42a-44d3-993d-e7492e732b34
https://github.com/user-attachments/assets/80ae7455-0e5d-4f6f-80ae-eec464d5b20a

**Comment by viv223345** [comment]
Using ec_probe, I think I may have found the register: 0x6A
Still not confirmed, though, and further testing is required.
Used s-tui and stress<sup>AUR</sup> to stress my CPU.

**Comment by viv223345** [comment]
> learning those kind of tools

It wasn't too difficult since it's pretty well [documented](https://github.com/nbfc-linux/nbfc-linux/blob/main/doc/ec_probe.1.md). Check it out! :D

> not a hardware dev

I'm not a dev at all - still in HS 😅

> But when [I asked for help](https://discord.com/channels/908873022105079848/1353041325292781659) and

Link isn't working :(

> I spy an ite5570 in there

Ah, crap. ITE datasheets are usually not released to the public. This makes it even more difficult to get fan control working :(

Do check out ec_probe though! (more specifically, the monitor option) It's included with nbfc-linux (and for Windows there's [nbfc](https://github.com/hirschmann/nbfc)

I used ```ec-probe monitor -ci 2``` and while monitoring, I used NitroSense to switch between 0% and 100% fan speed. (Used Custom mode with both sliders at zero for 0%, and Max mode for 100%). This is what helped me find the 0x5C and 0x6A registers :)

I'm yet to test the registers with nbfc-linux, but I think it'll (hopefully) work

**Comment by MematiBas42** [comment]
Ahhh this fans are not working even close to their potential! When i load stress on cpu temp reaches 92 but fan is not running even close to NitroSense max fan mode...  I found a [repo](https://github.com/PXDiv/Div-Acer-Manager) about it but i am unable to compile drivers... But on old version of project by same Dev , i was able to run fans at max speed. So controlling is possible i just can say that. Will be reading your sharing guys, i hope we solve this proble...

**Comment by Kabouik** [comment]
I am also trying to make a configuration for an ITE5570 computer and hitting roadblocks. I would be curious to know if you have had any success wit h`ec_probe` @NatanAmorim, and if so, which register you've identified?

This is the chip identified by `superiotool`:

```
superiotool r
Found Aspeed AST2400 (id=0x00) at 0x4e
Found ITE IT5570E (id=0x5570, rev=0x2) at 0x4e
```

And a dump:

```
$ sudo superiotool --dump --extra-dump

superiotool r
Found Aspeed AST2400 (id=0x00) at 0x4e
Register dump:
idx 20 21 22 23 24 25 26 27  28 29 2a 2b 2c 2d 2e 2f
val 55 70 02 01 00 00 00 00  00 00 00 00 01 00 12 00
def 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
LDN 0x02 (SUART1)
idx 30 60 61 70 71 f0
val 00 02 f8 03 02 00
def 00 03 f8 04 02 RR
LDN 0x03 (SUART2)
idx 30 60 61 70 71 f0
val 00 00 00 00 00 00
def 00 02 f8 03 02 00
LDN 0x04 (SWC)
idx 30 60 61 62 63 64 65 66  67 70 71
val 00 00 00 00 00 00 00 00  00 00 01
def 00 08 e6 08 e0 08 e4 08  e8 09 01
LDN 0x05 (Keyboard config (KBC))
idx 30 60 61 62 63 70 71 72  73 f0
val 00 00 00 00 00 0c 01 00  00 00
def 00 00 60 00 64 01 02 0c  02 83
LDN 0x07 (GPIO)
idx 30 38 70 71
val 00 00 00 00
def 00 00 0b 01
LDN 0x0b (SUART3)
idx 30 60 61 70 71 f0
val 00 00 00 00 00 00
def 00 03 e8 06 02 00
LDN 0x0c (SUART4)
idx 30 60 61 70 71 f0
val 00 00 00 00 00 00
def 00 02 e8 05 02 00
LDN 0x0d (iLPC2AHB)
idx 30 70 71 f0 f1 f2 f3 f4  f5 f6 f7 f8 fe
val 00 00 00 00 00 00 00 00  00 00 00 00 00
def 00 09 01 NA NA NA NA NA  NA NA NA 00 00
LDN 0x0e (Mailbox)
idx 30 60 61 70 71
val 00 00 00 00 00
def 00 08 c0 09 01
Found ITE IT5570E (id=0x5570, rev=0x2) at 0x4e
Register dump:
idx 20 21 22 23 24 25 26 27  28 29 2a 2b 2d
val 55 70 02 01 00 00 00 00  00 00 00 00 00
def 55 70 NA 01 RR 00 00 RR  RR RR RR RR 00
LDN 0x01 (Serial Port 1 (UART1))
idx 30 60 61 62 63 70 71 f0
val 00 03 f8 00 00 04 02 00
def 00 02 f8 00 00 03 02 00
LDN 0x02 (Serial Port 2 (UART2))
idx 30 60 61 62 63 70 71 f0
val 00 02 f8 00 00 03 02 00
def 00 02 f8 00 00 03 02 00
LDN 0x04 (System Wake-Up Control (SWUC))
idx 30 60 61 70 71
val 00 00 00 00 01
def 00 00 00 00 01
LDN 0x05 (KBC Mouse)
idx 30 70 71
val 00 0c 01
def 00 0c 01
LDN 0x06 (KBC Keyboard)
idx 30 60 61 62 63 70 71
val 01 00 60 00 64 01 03
def 00 00 60 00 64 01 01
LDN 0x0a (Consumer IR)
idx 30 60 61 70 71
val 00 03 10 00 02
def 00 03 10 00 02
LDN 0x0f (Shared Memory/Flash Interface (SMFI))
idx 30 60 61 70 71 f0 f1 f2  f3 f4 f5 f6 f9 fa fb fc
val 01 02 00 00 02 00 00 00  00 00 00 0b 00 00 00 00
def 00 00 00 00 02 00 00 00  00 00 00 00 00 00 00 01
LDN 0x10 (RTC-like Timer (RTC))
idx 30 60 61 62 63 64 65 66  67 68 69 70 71 f0 f1 f2  f3 f4 f5
val 01 09 12 05 10 00 00 00  00 00 00 08 01 00 49 4a  00 3f 3c
def 00 00 70 02 72 00 00 00  00 00 00 08 01 00 49 4a  00 00 00
LDN 0x11 (Power Management Interface Channel 1 (PMC1))
idx 30 60 61 62 63 70 71
val 01 00 62 00 66 00 01
def 00 00 62 00 66 01 01
LDN 0x12 (Power Management Interface Channel 2 (PMC2))
idx 30 60 61 62 63 64 65 70  71 f0
val 01 00 68 00 6c 00 00 00  01 00
def 00 00 68 00 6c 00 00 01  01 NA
LDN 0x13 (Serial Peripheral Interface (SSPI))
idx 30 60 61 70 71
val 00 03 00 00 02
def 00 03 00 00 02
LDN 0x14 (Platform Environment Control Interface (PECI))
idx 30 60 61
val 00 00 00
def 00 00 00
LDN 0x17 (Power Management Interface Channel 3 (PMC3))
idx 30 60 61 62 63 70 71
val 00 00 6a 00 6e 01 01
def 00 00 6a 00 6e 01 01
LDN 0x18 (Power Management Interface Channel 4 (PMC4))
idx 30 60 61 62 63 70 71
val 00 00 74 00 78 01 01
def 00 00 74 00 78 01 01
LDN 0x19 (Power Management Interface Channel 5 (PMC5))
idx 30 60 61 62 63 70 71
val 00 00 7a 00 7c 01 01
def 00 00 7a 00 7c 01 01
Environment controller (0x0005)
BRAM (0x0510)
```

All my attempts with `ec_probe` have failed. I did see some registers change values during an `ec monitor`, and I could write to them, but this would not alter fan speed, and they would quickly revert to another value a few seconds later. It also appears now that `ec_probe monitor` only shows me one register, while it used to show me 5 or 6 a few hours ago. I don't know what caused that, as I took care to write the values I read from the registers initially after I tried some custom values to change fan speed, and also the base functionality of the PC seems to be there too, with still the factory fan curve (which is horrendous).

**Comment by Kabouik** [comment]
If that is of any help, someone named @charlie on a community server found this detailed schematics: https://www.mikrocontroller.net/attachment/609783/nightsky_arx15.pdf (page 105).

A screenshot of the relevant page in case the PDF would vanish in the future:
![Image](https://github.com/user-attachments/assets/1e6a47c7-c363-4609-a7ea-aa333b6e3055)

I don't know if this can be used to guess registers? @braph, would you know?

**Comment by Kabouik** [comment]
Also interesting: https://github.com/frankcrawford/it87/issues/49

**Comment by LinoDB** [comment]
Hi, I have the same laptop model and found this thread very helpful! I'm also trying to figure out the EC register configuration using NitroSense and [RWEverything](http://rweverything.com/) on Windows. So far I found this, in case it's of any use:

| Register | Bit [0-7] | Function |
| --- | --- | --- |
| 0x5C and 0x5D | 0-7 | RPM of the CPU fan (2 bytes) |
| 0x6A and 0x6B | 0-7 | RPM of the GPU fan (2 bytes) |
| 0x64 | 0 | If set to 1, auto-mode takes effect and fan RPMs are reflected on 0x5C, 0x5D, 0x6A, and 0x6B |
| 0x64 | 4 | CPU manual mode |
| 0x64 | 5 | GPU manual mode |
| 0x55 | 0-3 | Reflects input value (?) of the CPU auto-mode [0-F] |
| 0x4F | 0-3 | Reflects input value (?) of the GPU auto-mode [0-F] |

I thought that `0x55` and `0x4F` were the respective fan's WriteRegisters, but I couldn't make it work. It seems to be the value the auto-mode applies and changing it leads to a short switch in fan speed until the auto-mode corrects it. Unfortunately, whatever NitroSense does to set a fixed fan speed doesn't seem to be reflected in the EC memory..

**Comment by TsunamiMommy** [comment]
Take a look at page 422 of the it5570 datasheet. That will give you a good map for the PWM control along with tachometer configuration of the chip itself. Some of the addresses you have do line up with the datasheet. However, you need to know what the full address is being sent to the EC register space when the program sends those commands. For PWM control, you'd be looking at 0x1800 on up. So you may see something like 0x185D instead of just 0x5D.  It's interesting that I see a 0x64 register here. Do you have the full address of that register? As 0x64 is just part of the EC address.

**Comment by PXDiv** [comment]
Wait guys, Nitro V uses wmi methods and nbfc uses  ec registers and both and not compatible.
Good Thing I made my own implementations (Yes there are several that i did) from just fan controls to whole Nitro-sense like functionallity; Here are the Projects you can use for ANV15-51 and newer acer laptops.
Div Acer Manager Max: https://github.com/PXDiv/Div-Acer-Manager-Max
Div Acer Manager Fan Controls: https://github.com/PXDiv/Div-Acer-Manager-Fan-Controls
Please star the projects to help spread it to other users

**Comment by NatanAmorim** [comment]
> DAMX may have to be reinstalled a couple times before it works. It breaks for me occasionally, and i have to reinstall the whole suite a couple times until the 'Power & Performance' tab shows up in the DAMX client.

Ok, I closed this issue because this is the nbfc-linux repository, DAMX has a [issue/feedback](https://github.com/PXDiv/Div-Acer-Manager-Max/issues) page, in one of the closed issues [DAMX #14](https://github.com/PXDiv/Div-Acer-Manager-Max/issues/14) it was stated that it's more tested on Ubuntu and that it works well with the kernel 6.14+, I did face the same problem you described while using Fedora tho [DAMX #10](https://github.com/PXDiv/Div-Acer-Manager-Max/issues/10), but **on Ubuntu 25.04 it works flawlessly for me** on ver `0.72`. I also plan to contribue to DAMX in the future, I loved the software.

**Comment by aspisvipera** [comment]
trying nbfc, coolercontrol and other things for 3-4 hours DAMX worked for me like wonders. if you are on arch, you might want to disable the Secure Boot because the linuwu-sense driver is unsigned. Ensure that you have "linux-headers" or the compilation can silently fail

- Here's my steps(It may be wrong cuz I kind of pressed all of the buttons and it somehow worked):

- 1. git clone https://github.com/PXDiv/Div-Acer-Manager-Max.git
- 2. cd Div-Acer-Manager-Max
- 3. cd scripts/
- 4. git clone https://github.com/PXDiv/Div-Linuwu-Sense.git Linuwu-Sense

- 5. chmod +x remote-setup.sh => to make it executable,

- 6. ./remote-setup-sh

proceed with the install and if you have problems with it you can:

- 7. curl -fsSL https://raw.githubusercontent.com/PXDiv/Div-Acer-Manager-Max/main/scripts/remoteSetup.sh -o /tmp/setup.sh && sudo bash /tmp/setup.sh


This curl must be fixing all of the problems and once you see 'Installation Complete'

You can reboot your laptop.

You should be able to just open Div Acer Manager or DAMX from your app menu.

I hope this helps.
